import os
import sqlite3
import psycopg2
from werkzeug.security import generate_password_hash

# SUPABASE POSTGRES CONNECTION
POSTGRES_URL = os.getenv('DATABASE_URL', '')

def setup_and_migrate():
    if not POSTGRES_URL:
        raise ValueError('DATABASE_URL environment variable is required to run Supabase migration.')

    print('[Supabase Migration] Connecting to Supabase PostgreSQL...')
    pg_conn = psycopg2.connect(POSTGRES_URL)
    pg_cursor = pg_conn.cursor()

    # 1. CREATE TABLES
    print('[Supabase Migration] Creating tables...')
    pg_cursor.execute('''
        CREATE TABLE IF NOT EXISTS public.dindis (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            palkhi_id TEXT UNIQUE NOT NULL,
            name TEXT NOT NULL,
            leader TEXT,
            contact TEXT,
            members INT DEFAULT 0,
            latitude DOUBLE PRECISION,
            longitude DOUBLE PRECISION,
            current_halt TEXT,
            status TEXT,
            status_label TEXT,
            last_updated TIMESTAMPTZ DEFAULT NOW()
        );

        CREATE TABLE IF NOT EXISTS public.volunteers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            phone TEXT UNIQUE NOT NULL,
            passcode_hash TEXT NOT NULL,
            status TEXT DEFAULT 'approved',
            created_at TIMESTAMPTZ DEFAULT NOW()
        );

        CREATE TABLE IF NOT EXISTS public.admins (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            palkhi_id TEXT REFERENCES public.dindis(palkhi_id) ON DELETE CASCADE,
            role TEXT DEFAULT 'palkhi_admin',
            is_approved INT DEFAULT 0,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            last_login TIMESTAMPTZ
        );

        CREATE TABLE IF NOT EXISTS public.dindi_members (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            palkhi_id TEXT REFERENCES public.dindis(palkhi_id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            age INT,
            health_note TEXT,
            created_at TIMESTAMPTZ DEFAULT NOW()
        );

        CREATE TABLE IF NOT EXISTS public.dindi_photos (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            palkhi_id TEXT REFERENCES public.dindis(palkhi_id) ON DELETE CASCADE,
            photo_url TEXT NOT NULL,
            caption TEXT,
            created_at TIMESTAMPTZ DEFAULT NOW()
        );

        CREATE TABLE IF NOT EXISTS public.seva_requests (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            type TEXT NOT NULL,
            provider_name TEXT NOT NULL,
            contact TEXT NOT NULL,
            location_name TEXT NOT NULL,
            description TEXT,
            latitude DOUBLE PRECISION,
            longitude DOUBLE PRECISION,
            active INT DEFAULT 1,
            created_at TIMESTAMPTZ DEFAULT NOW()
        );

        CREATE TABLE IF NOT EXISTS public.checkins (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            family_code TEXT NOT NULL,
            latitude DOUBLE PRECISION,
            longitude DOUBLE PRECISION,
            timestamp TIMESTAMPTZ DEFAULT NOW()
        );
    ''')
    pg_conn.commit()
    print('[Supabase Migration] Tables created successfully!')

    # 2. MIGRATE EXISTING SQLITE DATA
    sqlite_path = os.path.join(os.path.dirname(__file__), '..', 'hari_marg.db')
    if os.path.exists(sqlite_path):
        print(f'[Supabase Migration] Reading SQLite data from {sqlite_path}...')
        sq_conn = sqlite3.connect(sqlite_path)
        sq_conn.row_factory = sqlite3.Row

        # Migrate Dindis
        dindis = sq_conn.execute('SELECT * FROM dindis').fetchall()
        for d in dindis:
            pg_cursor.execute('''
                INSERT INTO public.dindis (palkhi_id, name, leader, contact, members, latitude, longitude, current_halt, status, status_label)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (palkhi_id) DO UPDATE SET
                    name = EXCLUDED.name,
                    leader = EXCLUDED.leader,
                    contact = EXCLUDED.contact,
                    members = EXCLUDED.members,
                    latitude = EXCLUDED.latitude,
                    longitude = EXCLUDED.longitude,
                    current_halt = EXCLUDED.current_halt,
                    status = EXCLUDED.status,
                    status_label = EXCLUDED.status_label
            ''', (d['palkhi_id'], d['name'], d['leader'], d['contact'], d['members'], d['lat'], d['lng'], d['current_halt'], d['status'], d['status_label']))

        # Migrate Volunteers with salted password hashing
        volunteers = sq_conn.execute('SELECT * FROM volunteers').fetchall()
        for v in volunteers:
            # Hash plaintext passcodes securely
            raw_pass = v['passcode']
            pass_hash = generate_password_hash(raw_pass) if not raw_pass.startswith('pbkdf2:') else raw_pass
            pg_cursor.execute('''
                INSERT INTO public.volunteers (name, phone, passcode_hash, status)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (phone) DO UPDATE SET
                    passcode_hash = EXCLUDED.passcode_hash,
                    status = EXCLUDED.status
            ''', (v['name'], v['phone'], pass_hash, v['status']))

        # Migrate Members
        members = sq_conn.execute('SELECT * FROM dindi_members').fetchall()
        for m in members:
            pg_cursor.execute('''
                INSERT INTO public.dindi_members (palkhi_id, name, age, health_note)
                VALUES (%s, %s, %s, %s)
            ''', (m['palkhi_id'], m['name'], m['age'], m['health_note']))

        # Migrate Photos
        photos = sq_conn.execute('SELECT * FROM dindi_photos').fetchall()
        for p in photos:
            pg_cursor.execute('''
                INSERT INTO public.dindi_photos (palkhi_id, photo_url, caption)
                VALUES (%s, %s, %s)
            ''', (p['palkhi_id'], p['photo_url'], p['caption']))

        # Migrate Seva Requests
        sevas = sq_conn.execute('SELECT * FROM seva_requests').fetchall()
        for s in sevas:
            pg_cursor.execute('''
                INSERT INTO public.seva_requests (type, provider_name, contact, location_name, description, latitude, longitude, active)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            ''', (s['type'], s['provider_name'], s['contact'], s['location_name'], s['description'], s['latitude'], s['longitude'], s['active']))

        sq_conn.close()
        pg_conn.commit()
        print('[Supabase Migration] SQLite data migrated to Supabase successfully!')

    pg_cursor.close()
    pg_conn.close()
    print('[Supabase Migration] COMPLETED!')

if __name__ == '__main__':
    setup_and_migrate()
